services:
  db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatbot_db
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-ragbot123!
      - ALLOWED_HOSTS=*
      - OPENAI_API_KEY=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
      - DB_NAME=chatbot_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    command: >
      sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application"
